services:
  mongodb-test:
    container_name: mongodb-test
    image: 'mongo:latest'
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongodb-test-data:/data/db
    environment:
      - 'MONGO_INITDB_DATABASE=payment_flux_test'

  redis:
    container_name: redis-cache
    image: 'redis:alpine'
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  mongodb-test-data:
    driver: local
  redis-data:
    driver: local