spring:
  application:
    name: payments-flux

  mongodb:
    uri: mongodb://localhost:27018/payment_flux_test
    auto-index-creation: true

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis